---
- hosts: cisco
  vars:
  - results: results
  tasks:
  - file: path={{results}} state=directory
    run_once: true
  - ios_facts:
    register: result
  - copy: content="{{result.ansible_facts|to_nice_yaml(indent=4)}}" dest=etc/ansible/{{results}}/{{inventory_hostname}}.yml
- hosts: arista
  vars:
  - results: results
  tasks:
  - file: path={{results}} state=directory
    run_once: true
  - eos_facts:
    register: result
  - copy: content="{{result.ansible_facts|to_nice_yaml(indent=4)}}" dest=etc/ansible/{{results}}/{{inventory_hostname}}.yml
